---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    package:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:
    
    - name: Add user Legolas
      tags: always,user
      user:
        name: Legolas
          #state: absent
        groups: root
        shell: /bin/bash


  
- hosts: servers1
  become: true
  tasks:

  - name: Install htop and firefox Ubuntu
    package:
      name: 
        - htop
        - firefox
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: Install firefox and htop CentOS
    package:
      name: 
        - firefox
        - htop
      state: absent
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.4"


- hosts: servers2
  become: true
  tasks:

    - name: Install htop on servers2
      tags: htopForServers2,htop,nginx
      package:
        name:
          - nginx
          - htop
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: Start nginx service
      tags: website,startser
      service:
        name: nginx
        state: started
        enabled: yes
      when: ansible_distribution == "Ubuntu"
