---

- hosts: all
  become: true
  tasks:

  - name: Install htop and firefox Ubuntu
    apt:
      name: 
        - htop
        - firefox
      state: absent
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install firefox and htop CentOS
    yum:
      name: 
        - firefox
        - htop
      state: absent
      update_cache: yes
    when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.4"
